CREATE TABLE occurrences (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  BO_YEAR INTEGER NOT NULL,
  BO_NUMBER INTEGER NOT NULL,
  BO_BEGIN_TIME TEXT NOT NULL,
  BO_EMISSION_TIME TEXT NOT NULL,
  DATE TEXT NOT NULL,
  PERIOD CHAR NOT NULL,
  IS_FLAGRANT BOOL NOT NULL,
  LATITUDE REAL NOT NULL,
  LONGITUDE REAL NOT NULL,
  PLACE_DESCRIPTION TEXT NOT NULL,
  POLICE_STATION_NAME TEXT NOT NULL,
  POLICE_STATION_CIRCUMSCRIPTION TEXT NOT NULL,
  RUBRIC TEXT NOT NULL,
  FATAL_VICTIM BOOL,
  PERSON_SEX TEXT,
  PERSON_AGE INTEGER,
  PERSON_SKIN_COLOR TEXT,
  LINKED_NATURE TEXT,
  UNIQUE (BO_YEAR, BO_NUMBER, POLICE_STATION_NAME)
);

CREATE VIRTUAL TABLE occurrences_index USING rtree(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	minLng, maxLng, -- Minimum and maximum X coordinate
	minLat, maxLat  -- Minimum and maximum Y coordinate
);